export const optionsData = [
    { value: 'Maharashtra', label: 'Maharashtra' },
    { value: 'Karnataka', label: 'Karnataka' },
    { value: 'TamilNadu', label: 'TamilNadu' },
    { value: 'Kerala', label: 'Kerala' },
    { value: 'Andhra Pradesh', label: 'Andhra Pradesh' },
    { value: 'West Bengal', label: 'West Bengal' },
    { value: 'Chhattisgarh', label: 'Chhattisgarh' },
    { value: 'Madhya Pradesh', label: 'Madhya Pradesh' },
    { value: 'Jharkhand', label: 'Jharkhand' },
    { value: 'Rajasthan', label: 'Rajasthan' },
    { value: 'Gujarat', label: 'Gujarat' },
    { value: 'Delhi', label: 'Delhi' },
    { value: 'Haryana', label: 'Haryana' },
    { value: 'Punjab', label: 'Punjab' },
    { value: 'Uttar Pradesh', label: 'Uttar Pradesh' },
    { value: 'Himachal Pradesh', label: 'Himachal Pradesh' },
]

export const optionsWithGroupsData = [
    { value: 'Maharashtra', label: 'Maharashtra', region: 'central' },
    { value: 'Karnataka', label: 'Karnataka', region: 'south' },
    { value: 'TamilNadu', label: 'TamilNadu', region: 'south' },
    { value: 'Kerala', label: 'Kerala', region: 'south' },
    { value: 'Andhra Pradesh', label: 'Andhra Pradesh', region: 'south' },
    { value: 'West Bengal', label: 'West Bengal', region: 'east' },
    { value: 'Chhattisgarh', label: 'Chhattisgarh', region: 'central' },
    { value: 'Madhya Pradesh', label: 'Madhya Pradesh', region: 'central' },
    { value: 'Jharkhand', label: 'Jharkhand', region: 'north' },
    { value: 'Rajasthan', label: 'Rajasthan', region: 'west' },
    { value: 'Gujarat', label: 'Gujarat', region: 'west' },
    { value: 'Delhi', label: 'Delhi', region: 'north' },
    { value: 'Haryana', label: 'Haryana', region: 'north' },
    { value: 'Punjab', label: 'Punjab', region: 'north' },
    { value: 'Uttar Pradesh', label: 'Uttar Pradesh', region: 'north' },
    { value: 'Himachal Pradesh', label: 'Himachal Pradesh', region: 'north' }
];
export const optionsWithGroups = [
    { value: 'Maharashtra', label: 'Maharashtra', optionGroup: 'central' },
    { value: 'Karnataka', label: 'Karnataka', optionGroup: 'south' },
    { value: 'TamilNadu', label: 'TamilNadu', optionGroup: 'south' },
    { value: 'Kerala', label: 'Kerala', optionGroup: 'south' },
    { value: 'Andhra Pradesh', label: 'Andhra Pradesh', optionGroup: 'south' },
    { value: 'West Bengal', label: 'West Bengal', optionGroup: 'east' },
    { value: 'Chhattisgarh', label: 'Chhattisgarh', optionGroup: 'central' },
    { value: 'Madhya Pradesh', label: 'Madhya Pradesh', optionGroup: 'central' },
    { value: 'Jharkhand', label: 'Jharkhand', optionGroup: 'north' },
    { value: 'Rajasthan', label: 'Rajasthan', optionGroup: 'west' },
    { value: 'Gujarat', label: 'Gujarat', optionGroup: 'west' },
    { value: 'Delhi', label: 'Delhi', optionGroup: 'north' },
    { value: 'Haryana', label: 'Haryana', optionGroup: 'north' },
    { value: 'Punjab', label: 'Punjab', optionGroup: 'north' },
    { value: 'Uttar Pradesh', label: 'Uttar Pradesh', optionGroup: 'north' },
    { value: 'Himachal Pradesh', label: 'Himachal Pradesh', optionGroup: 'north' }
];